project:
  type: website
  output-dir: docs

website:
  title: "R Café"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/intro.qmd
        text: Foundations of R

execute: 
  echo: TRUE

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  revealjs:
    css: styles.css
