project:
  type: website
  output-dir: docs

website:
  title: "rcafe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
execute: 
  echo: TRUE

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  revealjs:
    css: styles.css



