project:
  type: website
  output-dir: docs

website:
  title: "R Café"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/intro.qmd
        text: Getting started with R and Git
      - href: slides/tidyverse.qmd
        text: R programming with tidyverse
      - href: slides/gtsummary.qmd
        text: Quarto and gtsummary

execute: 
  echo: TRUE

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  revealjs:
    css: styles.css
