---
title: "Welcome to R Café"
format: html
---

## Duration
3 weeks of study + 1 week of extra content (if any) and closing remarks

## Structure
- 3-hour face-to-face sessions per day, 1 day per week
- Take home exercises given between face-to-face sessions

## R Café helpful shortcuts
- [Teams Tech support channel](https://teams.microsoft.com/l/channel/19%3AGyu0GBNtFFuDmjrVqXsrTYScHLPgP5bpTDLOoaJEeaE1%40thread.tacv2/Tech%20support?groupId=6abc7e7a-0132-4ec2-afa7-393d89c247d8&tenantId=22514748-bbda-4cb8-9795-bfa3fbeec018&ngc=true&allowXTenantAccess=true){target="_blank"}
- [Main GitHub repository](https://github.com/OUCRU-Modelling/R-cafe){target="_blank"}
- [Theoretical slides](https://oucru-modelling.github.io/R-cafe-materials/){target="_blank"}
- [Additional handouts and instructions](https://github.com/OUCRU-Modelling/R-cafe-materials/tree/main/additional_handouts/day_1){target="_blank"}
- Current instructor roster:
	- Thinh Ong Phuc (thinhop\@oucru.org)
	- Anh Phan Truong Quynh (anhptq\@oucru.org)
	- Hung Tran Thai (hungtt\@oucru.org)
	- Tuyen Huynh (tuyenhn\@oucru.org)
	- Hai Ho Bich (haihb\@oucru.org)

## Agenda
1. [Getting started with R and Git (day 1)](slides/intro.qmd){target="_blank"}
	- **Part 1**: Setup (45') - *Tuyen & QA*
		- What is R Café & Agenda (5')
		- Brief introduction to Git, GitHub, and GitHub Desktop
			- Goal: Publish your own branch on R Café's GitHub repository
		- Rstudio (20')
			- Goal: Create RStudio project
			- Goal: Everyone create and push their first commit onto their own branch
		- Navigate GitHub
	- **Part 2**: Foundations of R (60') - *QA*
		- Variables & Functions & Packages (with outline)
		- Exercises
			- Goal: Create a function and push to GitHub
			- Goal: Create issues and comment on each other's issues on GitHub
	- **Break** (15')
	- **Part 3**: Data manipulation in R (45') - *QA*
		- Data management
		- Take-home exercises setup

2. [R programming with `tidyverse` (day 2)](slides/tidyverse.qmd){target="_blank"}
	- **Into the `tidyverse`**
		- What is `tidyverse`?
		- Why should we use it?
		- How do we use it?
		- Piping with `%>%`
	- Exercise
	- **Vectorise R functions**
		- Vectors and vectorisation
		- Vectorisation with `map()`
		- `tidyverse` style vs. base R style
	- **`ggplot2` for data visualisation**
		- Grammar of graphics
	- Exercise
  
3. [Quarto & `gtsummary` (day 3)](slides/gtsummary.qmd){target="_blank"}
	- [Intro to Quarto](slides/quarto.qmd){target="_blank"}
	- Reproducible tables
		- Descriptive tables
		- Statistical inference
		- Univariate analysis
		- Multivariate analysis

## Take-home exercises
1. [Initial Data Analysis - IDA (with `skimr`)](takehome_exercises/day1.qmd){target="_blank"}
	- Generate questions around your data
	- Customize your summary table output
	- Simple visualization data, e.g. histogram
	- Calculate statistics, e.g. correlation, collinearity
2. [Data transformation](takehome_exercises/day2.qmd){target="_blank"}
	- Data cleaning and filtering
	- Data transformation
	- Factor your data (with `forcats`)
	- Data visualization (with `ggplot2`)
3. Analysis with `gtsummary`
	- Demographic summary
	- Statistical tests, e.g. t-test, chi-sq, fisher-exact, OR, etc.
4. Generate report with Quarto
	- Citation (inline footnote and reference)

## Capstone hint
1. [Capstone hint 1](slides/capstone_hint_1.qmd)